### PR TITLE
build: Add cross-media-measurement-api@0.65.0

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/53)

**Review by renjiezh — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/53)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/53#-O4Mb1SX7v6n58xo-odc:-O4Mb1SX7v6n58xo-odd:b-1c9ef9) (no related file):*
Seems files are not added in the commit.

___

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/53)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @renjiezh)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/53#-O4Mb1SX7v6n58xo-odc:-O4MbTrbBSFebSgl1-SP:b-896fix) (no related file):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Seems files are not added in the commit.
</blockquote></details>

Done.

___

**Review by renjiezh — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/53)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
