### PR TITLE
Add virtual-people-common@0.4.0.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/6)

**Review by riemanli — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/6)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`modules/virtual-people-common/0.4.0/MODULE.bazel` line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/6#-NnpF1taDra0Y2gYECOq:-NnpF1taDra0Y2gYECOr:bsya0iz) ([raw file](https://github.com/world-federation-of-advertisers/bazel-registry/blob/c0d4e3e81a9b300a4c9b66390fd3270ffd513583/modules/virtual-people-common/0.4.0/MODULE.bazel#L18)):*
> ```Starlark
> bazel_dep(
>     name = "protobuf",
>     version = "21.7",
> ```

Is this the most recent version in the registry? Is it possible to bump to more recent version like 23.4? I remember I had some compatibility issue when using 21.7 for Python gRPC. Don't remember the exact details tho. If it's not possible to have 23.4, I can dig more after this PR.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`modules/virtual-people-common/0.4.0/MODULE.bazel` line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/6#-NnpF1taDra0Y2gYECOq:-NnpKcgr9v2me7En3sPc:btjugi) ([raw file](https://github.com/world-federation-of-advertisers/bazel-registry/blob/c0d4e3e81a9b300a4c9b66390fd3270ffd513583/modules/virtual-people-common/0.4.0/MODULE.bazel#L18)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Is this the most recent version in the registry? Is it possible to bump to more recent version like 23.4? I remember I had some compatibility issue when using 21.7 for Python gRPC. Don't remember the exact details tho. If it's not possible to have 23.4, I can dig more after this PR.
</blockquote></details>

It looks like 23.1 got added to BCR (see https://registry.bazel.build/modules/protobuf), but rules_proto still depends on 21.7. We could try bumping it, but I'm not sure what'll happen.

Regardless, this PR is too late to change it. All this is doing is copying what's already in virtual-people-common to our registry. See https://github.com/world-federation-of-advertisers/virtual-people-common/blob/main/MODULE.bazel

**Review by riemanli — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
