### PR TITLE
Update README with instructions for adding a module version.

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/5)

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/5)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`README.md` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/5#-NnBfJtp-JmXMiKSMjkx:-NnBfJtp-JmXMiKSMjky:b9ea9g6) ([raw file](https://github.com/world-federation-of-advertisers/bazel-registry/blob/22cd3b8b134924fbb876aa672a6d7bfa290ed74f/README.md#L27)):*
> ```Markdown
>     *   Warnings related to BCR maintainer review and use of GitHub source
>         archives can be ignored.
> 3.  Create a pull request for the generated files, excluding `presubmit.yml` and
> ```

what about adding these to .gitignore?
___
*[`README.md` line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/5#-NnBfPof60u2nZC3hiQA:-NnBfPof60u2nZC3hiQB:b-urejnc) ([raw file](https://github.com/world-federation-of-advertisers/bazel-registry/blob/22cd3b8b134924fbb876aa672a6d7bfa290ed74f/README.md#L30)):*
> ```Markdown
>     the `.json` file that's generated in the working directory.
> 
> If you get an error related to `presubmit.yml` not being found, you can add an
> ```

why not just have the tool touch the file?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/5)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`README.md` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/5#-NnBfJtp-JmXMiKSMjkx:-Nnf6qqe2Ayr20WV-YT1:b-ydonir) ([raw file](https://github.com/world-federation-of-advertisers/bazel-registry/blob/71e924d543ba6c9275d94388c6592e23cabc34a8/README.md#L27)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what about adding these to .gitignore?
</blockquote></details>

Done. Good idea.
___
*[`README.md` line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/5#-NnBfPof60u2nZC3hiQA:-Nnf6nAq8qRiygjBX2Io:byfjpmc) ([raw file](https://github.com/world-federation-of-advertisers/bazel-registry/blob/71e924d543ba6c9275d94388c6592e23cabc34a8/README.md#L30)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why not just have the tool touch the file?
</blockquote></details>

The tool is external. We have no control over it.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/5)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/5)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
