### PR TITLE
Clarify step for copying/editing MODULE.bazel

### PR DESCRIPTION
**Pull request by SanjayVas**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/33)

**Review by kungfucraig — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/33)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`README.md` line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/33#-NuWFa6e-gOBEs_Empaf:-NuWFa6e-gOBEs_Empag:b-aksyxk) ([raw file](https://github.com/world-federation-of-advertisers/bazel-registry/blob/ac9670b0acbd274e964f79c76e5e68253341f5e0/README.md#L20)):*
> ```Markdown
> 
> 1.  Make a copy of the `MODULE.bazel` file from the module source, editing it to
>     specify the correct version.
> ```

This version must match the one you provide the tool when prompted.
___
*[`README.md` line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/33#-NuWEQ7u87IqFz3IMed1:-NuWEQ7u87IqFz3IMed2:bncwsou) ([raw file](https://github.com/world-federation-of-advertisers/bazel-registry/blob/ac9670b0acbd274e964f79c76e5e68253341f5e0/README.md#L23)):*
> ```Markdown
> 2.  Run the tool, following the input prompts.
>     *   Choose Yes at the prompt for specifying a MODULE.bazel file, specifying
>         the copy from (1).
> ```

Can you say something about the strip_prefix value? 
___
*[`README.md` line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/33#-NuWEcoW5y8i_1vnAj6Y:-NuWEcoW5y8i_1vnAj6Z:b-44xxfx) ([raw file](https://github.com/world-federation-of-advertisers/bazel-registry/blob/ac9670b0acbd274e964f79c76e5e68253341f5e0/README.md#L24)):*
> ```Markdown
>     *   Choose Yes at the prompt for specifying a MODULE.bazel file, specifying
>         the copy from (1).
>     *   Choose No for the remaining Yes/No prompts.
> ```

This is a lot of pedantry, but maybe it'll help the next person... 

* Choose "No" for all prompts except the one for specifying a MODULE.bazel file.
* Specify the file path from (1) for the value of the MODULE.bazel file.

* If prompted to enter a homepage URL for an existing module, ensure you have not made a typo when specifying the name of the module.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/33)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @kungfucraig)

___
*[`README.md` line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/33#-NuWFa6e-gOBEs_Empaf:-NuWId5g8US2UaLm1Ykl:bzgdanc) ([raw file](https://github.com/world-federation-of-advertisers/bazel-registry/blob/ac9670b0acbd274e964f79c76e5e68253341f5e0/README.md#L20)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

This version must match the one you provide the tool when prompted.
</blockquote></details>

Done (mentioned in the tool section instead).
___
*[`README.md` line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/33#-NuWEQ7u87IqFz3IMed1:-NuWIgPz1YHL2gImTl48:bol3985) ([raw file](https://github.com/world-federation-of-advertisers/bazel-registry/blob/ac9670b0acbd274e964f79c76e5e68253341f5e0/README.md#L23)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you say something about the strip_prefix value?
</blockquote></details>

Done.

Note that all of us who migrated from the `WORKSPACE` system using `http_archive` were quite familiar with this. It's also the same when using `archive_override`.
___
*[`README.md` line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/33#-NuWEcoW5y8i_1vnAj6Y:-NuWIyzw7XxQtuM3iUUo:bsmuy62) ([raw file](https://github.com/world-federation-of-advertisers/bazel-registry/blob/ac9670b0acbd274e964f79c76e5e68253341f5e0/README.md#L24)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

This is a lot of pedantry, but maybe it'll help the next person... 

* Choose "No" for all prompts except the one for specifying a MODULE.bazel file.
* Specify the file path from (1) for the value of the MODULE.bazel file.

* If prompted to enter a homepage URL for an existing module, ensure you have not made a typo when specifying the name of the module.
</blockquote></details>

Done, with some tweaks.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/33)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
