### PR TITLE
Readd cross-media-measurement-api 0.62.0

### PR DESCRIPTION
**Pull request by kungfucraig**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/31)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/31)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`modules/cross-media-measurement-api/0.62.0/MODULE.bazel` line 3 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/31#-NuVroeF41lfv9PY9ykZ:-NuVroeF41lfv9PY9yk_:bm1iit9) ([raw file](https://github.com/world-federation-of-advertisers/bazel-registry/blob/1b486be05b007e5b4ea92b16b5b442fafcbeab3d/modules/cross-media-measurement-api/0.62.0/MODULE.bazel#L3)):*
You dropped the edit specifying the version. From the README (emphasis added):

> Copy the `MODULE.bazel` for the module, **specifying the version**

This is also why you no longer have a `module_dot_bazel.patch`.

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/31)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`modules/cross-media-measurement-api/0.62.0/MODULE.bazel` line 3 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/31#-NuVroeF41lfv9PY9ykZ:-NuW7d3m2CIwVM46FPn6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/bazel-registry/blob/1b486be05b007e5b4ea92b16b5b442fafcbeab3d/modules/cross-media-measurement-api/0.62.0/MODULE.bazel#L3)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You dropped the edit specifying the version. From the README (emphasis added):

> Copy the `MODULE.bazel` for the module, **specifying the version**

This is also why you no longer have a `module_dot_bazel.patch`.
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/31)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Pull request merged**
