### PR TITLE
Add any-sketch-java 0.7.0

### PR DESCRIPTION
**Pull request by kungfucraig**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/44)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/44)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`modules/any-sketch-java/0.7.0/patches/module_dot_bazel.patch` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/44#-NzeS-QI2lfUw96lnhU6:-NzeS-QJ1uHSqXPhJTDe:b7uuayg) ([raw file](https://github.com/world-federation-of-advertisers/bazel-registry/blob/a6aca83a86bda255c177976a97cd8517d1d32e48/modules/any-sketch-java/0.7.0/patches/module_dot_bazel.patch#L1)):*
> ```Diff
> --- MODULE.bazel
> ```

This patch doesn't look right. It should just be adding a version line. I think you missed the version in your strip_prefix.

**Review by kungfucraig — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/44)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`modules/any-sketch-java/0.7.0/patches/module_dot_bazel.patch` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/44#-NzeS-QI2lfUw96lnhU6:-NzeWNFx1h9IIO31bS5m:bczff55) ([raw file](https://github.com/world-federation-of-advertisers/bazel-registry/blob/a6aca83a86bda255c177976a97cd8517d1d32e48/modules/any-sketch-java/0.7.0/patches/module_dot_bazel.patch#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This patch doesn't look right. It should just be adding a version line. I think you missed the version in your strip_prefix.
</blockquote></details>

Yeah, it's not right. You jumped on it before I added you. ;)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/bazel-registry/44)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Pull request merged**
